name: Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.48a62e12-80cb-4fc0-b4db-211f88adb14f }}
        tenant-id: ${{ secrets.e2b2a256-ebd3-4a3f-916e-37d2e85b9884}}
        subscription-id: ${{ secrets.4cdc700a-5678-4ac0-9653-3bf078a965d5 }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: dotnetacr123.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: |
        docker build . -t dotnetacr123.azurecr.io/dotnet:${{ github.sha }}
        docker push dotnetacr123.azurecr.io/dotnet:${{ github.sha }}     
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'azdotnet-1'
        images: 'dotnetacr123.azurecr.io/dotnet:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
